### PR TITLE
Merge in prototype code from @davidfowl

### PR DESCRIPTION
**Pull request by analogrelay**
Just a few minor helper types.

Note: I don't actually have access to push to this repo yet. @jeffhandley - You gave the team Write access but you may have to add this repo (and NuGet.Packaging) to the team in order for us to be able to push to them :).

### CODE REVIEW

**Comment by analogrelay** [comment]
If you sign off, one of you can probably merge this in while I wait for perms :P

**Comment by davidfowl** [comment]
I think we'll need to rename some things eventually but this is fine for now.

**Comment by analogrelay** [comment]
Yeah, VersionRange and NuGetVersionRange are confusing, but we can resolve that.

**Pull request merged**
